# Alternative GNU Make workspace makefile autogenerated by Premake

ifndef config
  config=debug_x64
endif

ifndef verbose
  SILENT = @
endif

ifeq ($(config),debug_x64)
  raylib_config = debug_x64
  RPGExample_config = debug_x64

else ifeq ($(config),debug.dll_x64)
  raylib_config = debug.dll_x64
  RPGExample_config = debug.dll_x64

else ifeq ($(config),release_x64)
  raylib_config = release_x64
  RPGExample_config = release_x64

else ifeq ($(config),release.dll_x64)
  raylib_config = release.dll_x64
  RPGExample_config = release.dll_x64

else
  $(error "invalid configuration $(config)")
endif

PROJECTS := raylib RPGExample

.PHONY: all clean help $(PROJECTS) 

all: $(PROJECTS)

raylib:
ifneq (,$(raylib_config))
	@echo "==== Building raylib ($(raylib_config)) ===="
	@${MAKE} --no-print-directory -C build -f Makefile config=$(raylib_config)
endif

RPGExample: raylib
ifneq (,$(RPGExample_config))
	@echo "==== Building RPGExample ($(RPGExample_config)) ===="
	@${MAKE} --no-print-directory -C RPG -f Makefile config=$(RPGExample_config)
endif

clean:
	@${MAKE} --no-print-directory -C build -f Makefile clean
	@${MAKE} --no-print-directory -C RPG -f Makefile clean

help:
	@echo "Usage: make [config=name] [target]"
	@echo ""
	@echo "CONFIGURATIONS:"
	@echo "  debug_x64"
	@echo "  debug.dll_x64"
	@echo "  release_x64"
	@echo "  release.dll_x64"
	@echo ""
	@echo "TARGETS:"
	@echo "   all (default)"
	@echo "   clean"
	@echo "   raylib"
	@echo "   RPGExample"
	@echo ""
	@echo "For more information, see https://github.com/premake/premake-core/wiki"